name: Giphy generator

on:
  pull_request:
    types: [opened]
    
jobs:
  giphy-generator:
    runs-on: ubuntu-latest
    
    steps:
    - name: GIPHY Generator
      uses: IAmHughes/giphy-generator@v1.0.0
      
      
