# change!

name: 000-manual-gates

env:
  CI_RUN_ID: ${{ github.run_id }}
  VERSION: 1.0.0

on: 
  push:

jobs:
  build:
    runs-on: ["ubuntu-latest"]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2         

      - run: echo hola
  
  deploy-qa:
    runs-on: ["ubuntu-latest"]

    needs: ["build"]

    environment:
      name: qa

    steps:
      - uses: actions/checkout@v2

      - run: echo Adios
