name: Show commit info

env:
  COMMIT_ID: ${{ github.event.head_commit.id }}
  COMMIT _MSG: ${{ github.event.head_commit.message }}
on:
  workflow_dispatch:
  
jobs:
  print_commit_info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print_info
      run: |
        echo Last commit ID: ${{ env.COMMIT_ID }}
        echo Last commit mesage: ${{ env.COMMIT_MSG }}
