name: Show commit info

on: workflow_dispatch
  branches: main
  
jobs:
  runs-on: ubuntu-latest
  steps:
  - name: print_info
    run: |
      echo Last commit ID: ${{ github.event.head_commit.id }}
      echo Last commit mesage: ${{ github.event.head_commit.message }}
