name: Show commit info

on:
  workflow_dispatch:
  
jobs:
  print_commit_info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : GITHUB CONTEXT
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: print_info
      run: |
        echo Last commit ID: ${{ github.sha }}
